"use client";

import { QuizItem } from "./SrsQuiz";
import DOMPurify from "dompurify";
import { useState, useEffect } from "react";
import ItemModal from "@/app/components/ItemModal";

type NoteSaveState = "idle" | "saving" | "saved" | "error";

export function QuizNoteManager({ 
  itemId, 
  initialNote,
  onSaveSuccess 
}: { 
  itemId: number, 
  initialNote: string,
  onSaveSuccess?: (note: string) => void 
}) {
  const [note, setNote] = useState(initialNote);
  const [saveState, setSaveState] = useState<NoteSaveState>("idle");

  useEffect(() => {
    setNote(initialNote || "");
    setSaveState("idle");
  }, [itemId, initialNote]);

  const handleSave = async () => {
    setSaveState("saving");
    try {
      const res = await fetch("/api/notes", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ itemId, content: note }),
      });
      if (!res.ok) throw new Error("Save failed");
      setSaveState("saved");
      if (onSaveSuccess) onSaveSuccess(note);
      setTimeout(() => setSaveState("idle"), 2500);
    } catch {
      setSaveState("error");
      setTimeout(() => setSaveState("idle"), 3000);
    }
  };

  const btnLabel =
    saveState === "saving" ? "Saving…" :
    saveState === "saved"  ? "Saved ✓" :
    saveState === "error"  ? "Error — retry" :
    "Save Note";

  return (
    <div className="note-section">
      <div className="note-header">
        <span className="note-title">📝 My Note</span>
      </div>
      <textarea
        className="note-textarea"
        value={note}
        onChange={(e) => {
          setNote(e.target.value);
          setSaveState("idle");
        }}
        placeholder="Add your personal note for this item..."
        rows={3}
      />
      <div className="note-footer">
        <button
          className={`note-save-btn note-save-${saveState}`}
          onClick={handleSave}
          disabled={saveState === "saving"}
        >
          {btnLabel}
        </button>
      </div>
    </div>
  );
}

export default function LessonModal({ item }: { item: QuizItem }) {
  const [modalTarget, setModalTarget] = useState<{ type: "item"; id: number } | { type: "radical"; wkSubjectId: number } | null>(null);

  return (
    <div className="cs-card-stack" style={{ padding: 0 }}>
      {modalTarget && (
         <ItemModal 
           target={modalTarget} 
           onClose={() => setModalTarget(null)}
           onNavigateItem={(id) => setModalTarget({ type: "item", id })}
           onNavigateRadical={(wkSubjectId) => setModalTarget({ type: "radical", wkSubjectId })}
         />
      )}

      {/* WaniKani Link & AI Notice */}
      {(item.wkLevel || item.meaningMnemonic) && item.type !== "radical" && (
        <div style={{ marginBottom: '8px' }}>
          {item.matchType !== "pseudo" ? (
            <a href={`https://www.wanikani.com/${item.type === "kanji" ? "kanji" : "vocabulary"}/${encodeURIComponent(item.characters)}`} target="_blank" rel="noopener noreferrer" className="tab-source-link">
              Open on WaniKani <span className="tab-source-arrow">↗</span>
            </a>
          ) : (
            <div style={{ padding: "12px", backgroundColor: "rgba(99, 102, 241, 0.1)", border: "1px solid rgba(99, 102, 241, 0.3)", borderRadius: "8px", fontSize: "14px", color: "var(--text-color)" }}>
              <strong>✨ AI Generated:</strong> This item is not officially on WaniKani. The mnemonics and context sentences below were generated by Gemini to provide an equivalent study experience.
            </div>
          )}
        </div>
      )}

      {/* Card: Meanings & Mnemonics */}
      {(item.meaningMnemonic || item.advancedMeanings || item.meanings.length > 0) && (
        <div className="cs-card">
          <h3 className="cs-card-title">
            <span className="cs-card-dot" style={{ backgroundColor: '#6366f1' }} />
            Meaning
          </h3>

          <div className="cs-meanings-row">
            {item.advancedMeanings ? (
              item.advancedMeanings.map((m, i) => (
                <span key={i} className={`cs-meaning-tag ${m.primary ? 'cs-primary' : ''}`}>
                  {m.meaning}
                </span>
              ))
            ) : (
              item.meanings.map((m, i) => (
                <span key={i} className={`cs-meaning-tag ${i === 0 ? 'cs-primary' : ''}`}>
                  {m}
                </span>
              ))
            )}
          </div>

          {/* Word Type */}
          {item.partsOfSpeech && item.partsOfSpeech.length > 0 && (
            <div style={{ marginBottom: "16px", display: "flex", gap: "12px", alignItems: "center" }}>
              <span style={{ fontSize: "11px", textTransform: "uppercase", color: "var(--text-muted)", fontWeight: "bold", letterSpacing: "1px" }}>
                WORD TYPE
              </span>
              <span style={{ color: "var(--text-primary)", fontSize: "15px" }}>
                {item.partsOfSpeech.join(", ")}
              </span>
            </div>
          )}

          {item.meaningMnemonic && (
            <div className="cs-mnemonic" dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(item.meaningMnemonic) }} />
          )}
          {item.meaningHint && (
            <div className="cs-hint">
              <strong>Hint:</strong> <span dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(item.meaningHint) }} />
            </div>
          )}
        </div>
      )}

      {/* Card: Reading & Mnemonic */}
      {item.type !== "radical" && (item.readingMnemonic || (item.advancedReadings && item.advancedReadings.length > 0) || (item.readings && item.readings.length > 0)) && (
        <div className="cs-card">
          <h3 className="cs-card-title">
            <span className="cs-card-dot" style={{ backgroundColor: '#10b981' }} />
            Reading
          </h3>

          {item.advancedReadings && item.type === "kanji" ? (
            <div className="cs-readings-grid">
              {Object.entries(
                item.advancedReadings.reduce((acc, r) => {
                  const t = r.type || "nanori";
                  if (!acc[t]) acc[t] = [];
                  acc[t].push(r);
                  return acc;
                }, {} as Record<string, typeof item.advancedReadings[0][]>)
              ).map(([type, rArr]) => (
                <div key={type} className="cs-reading-group">
                  <span className="cs-reading-type">{type === 'onyomi' ? "On'yomi" : type === 'kunyomi' ? "Kun'yomi" : "Nanori"}</span>
                  <div className="cs-reading-values">
                    {rArr.map((r, i) => (
                      <span key={i} className={r.primary ? 'cs-reading-primary' : ''}>{r.reading}</span>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          ) : item.advancedReadings && item.advancedReadings.length > 0 ? (
            <div className="cs-readings-grid">
              <div className="cs-reading-group">
                <span className="cs-reading-type">Reading</span>
                <div className="cs-reading-values">
                  {item.advancedReadings.map((r, i) => (
                    <span key={i} className={r.primary ? 'cs-reading-primary' : ''}>{r.reading}</span>
                  ))}
                </div>
              </div>
            </div>
          ) : item.readings && item.readings.length > 0 ? (
            <div className="cs-readings-grid">
              <div className="cs-reading-group">
                <span className="cs-reading-type">Reading</span>
                <div className="cs-reading-values">
                  {item.readings.map((r, i) => (
                    <span key={i} className={i === 0 ? 'cs-reading-primary' : ''}>{r}</span>
                  ))}
                </div>
              </div>
            </div>
          ) : null}

          {item.readingMnemonic && (
            <div className="cs-mnemonic" dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(item.readingMnemonic) }} />
          )}
          {item.readingHint && (
            <div className="cs-hint">
              <strong>Hint:</strong> <span dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(item.readingHint) }} />
            </div>
          )}
        </div>
      )}

      {/* Card: Radicals */}
      {(item.radicals?.length || 0) > 0 && (
        <div className="cs-card">
          <h3 className="cs-card-title">
            <span className="cs-card-dot" style={{ backgroundColor: 'var(--accent-radical)' }} />
            Radicals
          </h3>
          <div className="srs-chip-grid">
            {item.radicals!.map((rad, idx) => (
              <div 
                key={idx} 
                className="srs-feature-chip radical-composition-chip"
                onClick={() => setModalTarget({ type: "radical", wkSubjectId: rad.id })}
                style={{ cursor: 'pointer' }}
              >
                <span className="srs-chip-kanji" style={{ color: 'var(--accent-radical)' }}>
                  {rad.characters || (rad.imageUrl ? <img src={rad.imageUrl} alt={rad.meaning} /> : "?")}
                </span>
                <span className="srs-chip-desc">{rad.meaning}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Card: Kanji Composition */}
      {(item.componentKanji?.length || 0) > 0 && (
        <div className="cs-card">
          <h3 className="cs-card-title">
            <span className="cs-card-dot" style={{ backgroundColor: 'var(--accent-kanji)' }} />
            Kanji Composition
          </h3>
          <div className="srs-chip-grid">
            {item.componentKanji!.map((k, idx) => (
              <div 
                key={idx} 
                className="srs-feature-chip kanji-composition-chip"
                onClick={() => k.id && setModalTarget({ type: "item", id: k.id })}
                style={{ cursor: k.id ? 'pointer' : 'default' }}
              >
                <div className="srs-chip-main">{k.expression}</div>
                <div className="srs-chip-sub">{k.meaning}</div>
                <div className="srs-chip-meta">{k.jlptLevel || `WK Lv ${k.wkLevel}`}</div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Card: Context Sentences */}
      {item.contextSentences && item.contextSentences.length > 0 && (
        <div className="cs-card">
          <h3 className="cs-card-title">
            <span className="cs-card-dot" style={{ backgroundColor: '#f59e0b' }} />
            Context Sentences
          </h3>
          <div className="cs-sentences">
            {item.contextSentences.slice(0, 3).map((sentence, idx) => (
              <div key={idx} className="cs-sentence">
                <p className="cs-sentence-ja">{sentence.ja}</p>
                <p className="cs-sentence-en">{sentence.en}</p>
              </div>
            ))}
          </div>
        </div>
      )}
      
      {/* Card: Related Vocab */}
      {(item.relatedVocab?.length || 0) > 0 && (
        <div className="cs-card">
          <h3 className="cs-card-title">
            <span className="cs-card-dot" style={{ backgroundColor: 'var(--accent-vocab)' }} />
            Found In Vocabulary
          </h3>
          <div className="srs-chip-grid grammar-grid">
            {item.relatedVocab!.map((v, idx) => (
              <div 
                key={idx} 
                className="srs-grammar-chip vocab-chip-override"
                onClick={() => setModalTarget({ type: "item", id: v.id })}
                style={{ cursor: 'pointer' }}
              >
                <span className="srs-grammar-title" style={{ fontSize: '18px', fontWeight: 'bold' }}>{v.expression} <span style={{ fontSize: '13px', color: 'var(--text-muted)', fontWeight: 'normal' }}>{v.reading}</span></span>
                <span className="srs-grammar-meaning">{v.meaning}</span>
                <span className="srs-grammar-level">{v.jlptLevel?.toUpperCase() || ''}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Card: Used in Kanji */}
      {(item.usedInKanji?.length || 0) > 0 && (
        <div className="cs-card">
          <h3 className="cs-card-title">
            <span className="cs-card-dot" style={{ backgroundColor: 'var(--accent-kanji)' }} />
            Found In Kanji
          </h3>
          <div className="srs-chip-grid">
            {item.usedInKanji!.map((k, idx) => (
              <div 
                key={idx} 
                className="srs-feature-chip kanji-composition-chip"
                onClick={() => setModalTarget({ type: "item", id: k.id })}
                style={{ cursor: 'pointer' }}
              >
                <div className="srs-chip-main">{k.expression}</div>
                <div className="srs-chip-sub">{k.meaning}</div>
                <div className="srs-chip-meta">{k.jlptLevel?.toUpperCase() || ''}</div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
